title: Python Learning
description: Learning programme for python.
template:
  repo: python-learning-template
  name: python-learning
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
  - type: assignRegistrant
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
